package consultaspaginas;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author VBarrera
 */
public class ConsultasGobierno extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasGobierno
     */
    ConsultasPaginas paginas = new ConsultasPaginas();
    static Thread hilo;

    public ConsultasGobierno() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogEsperar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numDoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoDoc = new javax.swing.JComboBox<>();
        buscarDoc = new javax.swing.JButton();

        dialogEsperar.setIconImages(null);
        dialogEsperar.setUndecorated(true);
        dialogEsperar.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                dialogEsperarWindowClosing(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consultaspaginas/imagenes/lupa.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buscando Identificacion");

        javax.swing.GroupLayout dialogEsperarLayout = new javax.swing.GroupLayout(dialogEsperar.getContentPane());
        dialogEsperar.getContentPane().setLayout(dialogEsperarLayout);
        dialogEsperarLayout.setHorizontalGroup(
            dialogEsperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEsperarLayout.createSequentialGroup()
                .addGroup(dialogEsperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogEsperarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(dialogEsperarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        dialogEsperarLayout.setVerticalGroup(
            dialogEsperarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEsperarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas Gobierno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Numero Identificacion: ");

        numDoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numDoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numDoc.setToolTipText("");
        numDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numDocKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo de Documento:");

        tipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Cedula Extranjeria" }));

        buscarDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consultaspaginas/imagenes/lupa1.gif"))); // NOI18N
        buscarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tipoDoc))
                .addGap(18, 18, 18)
                .addComponent(buscarDoc)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDocActionPerformed

        // dispose();
        dialogEsperar.setVisible(true);
        dialogEsperar.setSize(400, 400);
        dialogEsperar.setLocationRelativeTo(this);
        String identidad = numDoc.getText();
        hilo = new Thread(new Runnable() {
            @Override
            public void run() {
                String policia = paginas.policia(identidad);
                String ofac = paginas.ofac(identidad);
                String procuraduria = paginas.procuraduria(identidad);
//                String policia = "policia1";
//                String ofac = "ofac1";
//                String procuraduria = "procuraduria1";
                apiDb(identidad, policia, ofac, procuraduria);

                JOptionPane.showMessageDialog(null,
                        "Identidad: " + identidad + "\n\n"
                        + "Policia: " + policia + "\n\n"
                        + "Ofac: " + ofac + "\n\n"
                        + "Procuraduria: " + procuraduria + "\n", "Detalles de Consulta", 1);
                dialogEsperar.dispose();
                numDoc.setText(null);
                setVisible(true);
            }
        });
        hilo.start();


    }//GEN-LAST:event_buscarDocActionPerformed
    void apiDb(String identidad, String policia, String ofac, String procuraduria) {
        String sHostName = null;
        String sNameUser = null;
        try {
            InetAddress address = InetAddress.getLocalHost();
            sHostName = address.getHostName();
            sNameUser = System.getProperty("user.name");
            //System.out.println(sHostName + " " + sNameUser);
        } catch (UnknownHostException ex) {
            Logger.getLogger(ConsultasGobierno.class.getName()).log(Level.SEVERE, null, ex);
        }
        OkHttpClient client = new OkHttpClient();
        MediaType mediaType = MediaType.parse("application/json");
        RequestBody body = RequestBody.create(mediaType, "{\n\t\"nombre_pc\":\"" + sHostName + "\",\n\t\"usuario\":\"" + sNameUser + "\",\n\t\"identif\":\"" + identidad + "\",\n\t\"ponal\":\"" + policia + "\",\n\t\"ofac\":\"" + ofac + "\",\n\t\"procura\":\"" + procuraduria + "\"\n}");
        Request request = new Request.Builder()
                .url("http://vr-nc-web-ap01/caja/public/api/consulta_gobierno")
                .post(body)
                .addHeader("X-Authorization-Token", "79721c90bf53f6ca79cae1d3241b72f6")
                .addHeader("X-Authorization-Time", "2017")
                .addHeader("Content-Type", "application/json")
                .addHeader("Cache-Control", "no-cache")
                .build();
        try {
            Response response = client.newCall(request).execute();
            System.out.println(response.body().string());
        } catch (IOException ex) {
            Logger.getLogger(ConsultasGobierno.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        paginas.cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void dialogEsperarWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogEsperarWindowClosing
        paginas.cerrar();
       
    }//GEN-LAST:event_dialogEsperarWindowClosing

    private void numDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numDocKeyTyped
      
    }//GEN-LAST:event_numDocKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasGobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasGobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasGobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasGobierno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultasGobierno().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDoc;
    private javax.swing.JDialog dialogEsperar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numDoc;
    private javax.swing.JComboBox<String> tipoDoc;
    // End of variables declaration//GEN-END:variables
}
